[project]
name = "vpmobil"
version = "3.0.2"
description = "API wrapper library for evaluating VpMobil substitution plans"
readme = "README.md"
requires-python = ">=3.8"
license = "EUPL-1.2"
authors = [
  { name = "Annhilati"},
  { name = "Joshi"}
]
dependencies = [
  "requests",
  "yarl",
  "pyyaml",
  "toml"
]
[project.optional-dependencies]
pdfs = ["pdfplumber"]

[project.urls]
"Homepage" = "https://github.com/annhilati/vpmobil-py"
"Documentation" = "https://annhilati.gitbook.com/vpmobil"
"Changelog" = "https://annhilati.gitbook.io/vpmobil/anderes/changelog"
"Repository" = "https://github.com/annhilati/vpmobil-py"
"Bug Tracker" = "https://github.com/annhilati/vpmobil-py/issues"
"Download" = "https://pypi.org/project/vpmobil/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["vpmobil", "vpmobil.extensions"]
include-package-data = true
